version: '3.7'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: authUsers
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"  # Default PostgreSQL port
    networks:
      - auth-network

  auth-service:
    image: auth-service-image
    container_name: auth-service-container
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/authUsers
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: auth_password
      CONFIG_SERVER_URL: http://host.docker.internal:9296
     # EUREKA_SERVER_ADDRESS: http://host.docker.internal:8761/eureka
    ports:
      - "9091:9091"
    networks:
      - auth-network

networks:
  auth-network:
