server:
  port: 8761

spring:
  application:
    name: service-registry  # Ensure correct spacing and name format

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # Correct property format
    fetchRegistry: false
